version: '3'

services:
  miaguila:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_DB: 'trips'
      POSTGRES_USER: 'miaguila'
      POSTGRES_PASSWORD: 'secret'